MyPortfolioProject/Controllers/SkillController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyPortfolioProject.DAL.Context;
using MyPortfolioProject.DAL.Entities;

namespace MyPortfolioProject.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SkillController : Controller
    {
        private readonly AppDbContext _context;
        public SkillController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var skills = _context.Skills.ToList();
            return View(skills);
        }
		[HttpGet]
		public IActionResult Create()
		{
			return View();
		}
		[HttpPost]
		public IActionResult Create(Skill skill)
		{
			_context.Skills.Add(skill);
			_context.SaveChanges();
			return RedirectToAction("Index");
		}
		[HttpGet]
		public IActionResult Update(int skillId)
		{
			var value = _context.Skills.Find(skillId);
			return View(value);
		}
		[HttpPost]
		public IActionResult Update(Skill skill)
		{
			_context.Skills.Update(skill);
			_context.SaveChanges();
			return RedirectToAction("Index");
		}

		public IActionResult Delete(int skillId)
		{
			var value = _context.Skills.Find(skillId);
			_context.Skills.Remove(value);
			_context.SaveChanges();
			return RedirectToAction("Index");
		}
	}
}

MyPortfolioProject/Views/Skill/Create.cshtml
@model Skill
@{
	ViewData["Title"] = "Create";
	Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="content" style="margin-bottom:20em;">
	<div class="container-fluid">
		<h4 class="page-title">Yetenekler</h4>
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-header">
						<div class="card-title">Yetenek Ekleme Sayfası</div>
					</div>
					<div class="card-body">

						<form method="post">
							<label>Yeteneğin Başlığı</label>
							<input type="text" asp-for="Title" class="form-control" />
							<br />
							<label>Yüzde Olarak Değeri</label>
							<input type="number" asp-for="Value" placeholder="Örn.: 90" class="form-control" />
							<br />
							<button class="btn btn-primary">Yetenek Ekle</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

MyPortfolioProject/Views/Skill/Index.cshtml
@model List<Skill>

@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="content" style="margin-bottom:20em;">
	<div class="container-fluid">
		<h4 class="page-title">Yetenekler</h4>
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-header">
						<div class="card-title">Yetenek Listesi</div>
					</div>
					<div class="card-body">
						<div class="card-sub">
							Yetenekler ile ilgili işlemleri aşağıdaki panelden yapabilirsiniz.
						</div>
						<table class="table mt-3">
							<thead>
								<tr>
									<th scope="col">Başlık</th>
									<th scope="col">Yüzde Olarak Değeri</th>
									<th scope="col">Sil</th>
									<th scope="col">Güncelle</th>
								</tr>
							</thead>
							<tbody>
								@foreach (var item in Model)
								{
									<tr>
										<td>@item.Title</td>
										<td>@item.Value%</td>
										<td><a data-id="@item.Id" asp-controller="Skill" asp-action="Update" asp-route-skillId="@item.Id" class="btn btn-success">Güncelle</a></td>
										<td><a data-id="@item.Id" asp-controller="Skill" asp-action="Delete" asp-route-skillId="@item.Id" class="btn btn-danger">Sil</a></td>
									</tr>
								}
							</tbody>
						</table>
						<a asp-controller="Skill" asp-action="Create" class="btn btn-outline-primary">Yeni Yetenek Girişi</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

MyPortfolioProject/Views/Skill/Update.cshtml
@model Skill
@{
	ViewData["Title"] = "Update";
	Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="content" style="margin-bottom:20em;">
	<div class="container-fluid">
		<h4 class="page-title">Yetenekler</h4>
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-header">
						<div class="card-title">Yetenek Güncelleme Sayfası</div>
					</div>
					<div class="card-body">

						<form method="post">
							<input type="hidden" asp-for="Id" />
							<label>Başlık</label>
							<input type="text" asp-for="Title" class="form-control" />
							<br />
							<label>Yüzde Olarak Değeri</label>
							<input type="number" asp-for="Value" placeholder="Örn.: 90" class="form-control" />
							<br />
							<button class="btn btn-primary">Yeteneği Güncelle</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>