MyPortfolioProject/Controllers/DefaultController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyPortfolioProject.Controllers
{
    public class DefaultController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MyPortfolioProject/Controllers/MessageController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyPortfolioProject.DAL.Context;
using MyPortfolioProject.DAL.Entities;

namespace MyPortfolioProject.Controllers
{
    [Authorize(Roles = "Admin")]
    public class MessageController : Controller
	{
        private readonly AppDbContext _context;

        public MessageController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Inbox()
		{
			var values = _context.Messages.ToList();
			return View(values);
		}

		public IActionResult ChangeIsReadToTrue(int id) // Mesaji okundu olarak isaretlemek icin
		{
			var value = _context.Messages.Find(id);
			value.IsRead = true;
			_context.SaveChanges();
			return RedirectToAction("Inbox");
		}

		public IActionResult ChangeIsReadToFalse(int id) // Mesaji okunmadi olarak isaretlemek icin
		{
			var value = _context.Messages.Find(id);
			value.IsRead = false;
			_context.SaveChanges();
			return RedirectToAction("Inbox");
		}

		public IActionResult DeleteMessage(int id)
		{
			var value = _context.Messages.Find(id);
			_context.Messages.Remove(value);
			_context.SaveChanges();
			return RedirectToAction("Inbox");
		}

		public IActionResult MessageDetail(int id)
		{
			var value = _context.Messages.Find(id);
            value.IsRead = true; // Mesaj detayina gidildiyse mesaj okundu bilgisi true yapiliyor.
            _context.SaveChanges();
            return View(value);
		}
		[HttpGet]
        public IActionResult SendMessage()
        {
            return View("~/Views/Shared/Components/_ContactComponentPartial/Default.cshtml");
        }
        [HttpPost]
		public IActionResult SendMessage(Message message) // Ana sayfadan gelen mesajlarin gonderimi
		{
            if (ModelState.IsValid)
            {
                message.SendDate = DateTime.Now;
                message.IsRead = false;
                _context.Messages.Add(message);
                _context.SaveChanges();
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }

    }
}

MyPortfolioProject/Views/Shared/Components/_AdminStatisticMessages/Default.cshtml
@model List<Message>

<div class="col-md-6">
    <div class="card" style="height:20em; overflow:auto;">
        <div class="card-header">
            <h4 class="card-title">Okunmamış Mesajlar</h4>
        </div>
        <div class="card-body">
            <table class="table table-head-bg-dark table-striped table-hover">
                @if (Model.Count != 0)
                {
                <thead>
                    <tr>
                        <th scope="col">Adı Soyadı</th>
                        <th scope="col">Konu</th>
                        <th scope="col">Tarih</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>           
                            <td>@item.NameSurname</td>
                            <td>@item.Subject</td>
                            <td>@item.SendDate.ToString("dd MMM yyyy HH:mm")</td>
                            <td> <a data-id="@item.Id" asp-controller="Message" asp-action="MessageDetail" asp-route-id="@item.Id" class="btn btn-outline-primary btn-sm"> Oku </a></td>           
                        </tr>
                    }

                    </tbody>
                }
                else
                {
                    <p class="text-center">Henüz yeni bir mesajınız yok.</p>
                }
            </table>
        </div>
    </div>
</div>